# Site settings
title: Iman Iif
description: A wedding invitation of Iman & Iif
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Iman & Iif
# user_description: lalalalalalala
user_title: 18 Juni 2022
# email: iman.iif.1443@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Quran Verse
verse: (QS Ar-Rum 21)
verse_content: Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir."

# Bride & Groom
bride: Iftitakhul Zakiah
groom: Achmad Iman Firmansyah
bride_parent: Bapak Muhammad Rif'an & Ibu Nasrowiyah Djaelani
groom_parent: Bapak Okarijandi Harun & Ibu Elly Sylviana

# Event details
date: Sabtu, 18 Juni 2022
akad_time: 09.00 - 10.00 WIB
reception_time1: 10.00 - 12.00 WIB
reception_time2: 13.00 - 15.00 WIB
location: Jl. Letjen. Pol. Soemarto, Gg. 14, no. 52, Purwanegara, Purwokerto Utara, Banyumas, Jawa Tengah

# Covid Protocol
protocol1: Menggunakan masker
protocol2: Menjaga jarak
protocol3: Mencuci tangan
protocol4: Memeriksa suhu tubuh
# protocol5: Tidak berjabat tangan

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
